name: Build APK (Kivy/Buildozer)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Этот экшен ставит всё нужное для Kivy/Buildozer: JDK, Android SDK, NDK, инструменты
      - name: Setup Kivy Build Environment
        uses: kivy/buildozer-action@v1
        with:
          python-version: '3.11'
          android-api: '31'
          android-ndk: '25b'

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: messenger-apk
          path: bin/*.apk
